# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'macOS 10.13'

steps:

- task: NodeTool@0
  displayName: 'Define Node to v9.11.2'
  inputs:
    versionSpec: '9.11.2'

- bash: |
    npm i -g npm@6.5
    /usr/local/bin/npm ci
    npm run bundle
  displayName: 'Build ReactNative'

- bash: ./gradlew $(gradle.flavor)
  displayName: 'Build Browser'

- bash: cp -r app/build/outputs/apk/*/debug/*-debug.apk $(Build.ArtifactStagingDirectory)
  displayName: 'Archive Builds'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish Cliqz Build'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app-cliqz-fat-debug.apk'
    artifactName: '$(Build.BuildId).CliqzAPK'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app-amazon-fat-debug.apk'
    artifactName: '$(Build.BuildId).AmazonAPK'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app-lumen-fat-debug.apk'
    artifactName: '$(Build.BuildId).LumenAPK'
    publishLocation: 'Container'